server.port: 8081
server.address=0.0.0.0
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=6m

# Database Configuration (based on screenshot)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1?oracle.jdbc.ReadTimeout=60000&oracle.net.CONNECT_TIMEOUT=10000
spring.datasource.username=ACETP
# The password was hidden in the screenshot. Please replace the placeholder below with the actual password.
spring.datasource.password=Aissa1000*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1700000
spring.datasource.hikari.minimum-idle=10

# Configuration des tailles de pool de threads (tuning cluster)
mq2db.si.poolSize=10
mq2db.processing.poolSize=8
mq2db.audit.poolSize=2
mq2db.claim.parallelism=1

# ---- REAPER SI (Agr?gateur Stateful) ----
mq2db.reaper.timeoutMs=600000
# Fr?quence de scan de la base pour forcer la lib?ration des lots orphelins (1 min)
mq2db.reaper.runIntervalMs=60000
mq2db.reaper.si.enabled=false

# ---- REAPER M?TIER (Messages bloqu?s IN_PROGRESS) ----
# ?ge ? partir duquel un traitement est consid?r? comme "pendu" (30 min)
mq2db.reaper.staleClaimAgeSeconds=1800
# Fr?quence de v?rification du stock "pendu" (5.5 min)
mq2db.reaper.fixedDelayMs=330000
mq2db.reaper.enabled=false

# ---- LOCK REAPER (Purge physique des verrous expir?s en base) ----
# ?ge max d'un verrou dans la table EF_SHARED_LOCK (10 min)
mq2db.lockreaper.ttlMinutes=10
# Fr?quence de nettoyage de la table des verrous (5 min)
mq2db.lockreaper.fixedDelayMs=300000
mq2db.lockreaper.enabled=true

# Expose tous les endpoints Actuator via JMX
spring.jmx.enabled=true

# Exposition Web (n?cessaire pour que l'onglet Endpoints d'IntelliJ soit riche)
management.endpoint.health.show-details=always

management.endpoints.web.exposure.include=*
management.endpoints.jmx.exposure.include=*


# Debug Logging
logging.level.root=info
logging.level.com.bnpparibas=info

